Default: &defaults
  database: angulicious.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: angulicious_test.sqlite3
  <<: *defaults

Staging:
  database: angulicious_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: angulicious_production.sqlite3
  poolsize: 100
  <<: *defaults
